//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_WEB.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ROP_WEB.Res.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Police.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genreral Info.
        /// </summary>
        public static string about1 {
            get {
                return ResourceManager.GetString("about1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string about2 {
            get {
                return ResourceManager.GetString("about2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string achivment {
            get {
                return ResourceManager.GetString("achivment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&apos;Dahirah Governorate Police Headquarter.
        /// </summary>
        public static string ADahirah {
            get {
                return ResourceManager.GetString("ADahirah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&apos;Dakiliyah Governorate Police Headquarter.
        /// </summary>
        public static string ADakiliyah {
            get {
                return ResourceManager.GetString("ADakiliyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Airport Security.
        /// </summary>
        public static string AirportSecurity {
            get {
                return ResourceManager.GetString("AirportSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Batinah Governorate North Police Headquarter.
        /// </summary>
        public static string AlBatinah {
            get {
                return ResourceManager.GetString("AlBatinah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Batinah Governorate South Police Headquarter.
        /// </summary>
        public static string AlBatinah1 {
            get {
                return ResourceManager.GetString("AlBatinah1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Buraimi Governorate Police Headquarter.
        /// </summary>
        public static string AlBuraimi {
            get {
                return ResourceManager.GetString("AlBuraimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string alig {
            get {
                return ResourceManager.GetString("alig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string alig2 {
            get {
                return ResourceManager.GetString("alig2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Wusta Governorate Police Headquarter.
        /// </summary>
        public static string AlWusta {
            get {
                return ResourceManager.GetString("AlWusta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Wusta Governorate Police Headquarter.
        /// </summary>
        public static string AlWustaGovernoratePoliceHeadquarter {
            get {
                return ResourceManager.GetString("AlWustaGovernoratePoliceHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambulance Division.
        /// </summary>
        public static string Ambulance {
            get {
                return ResourceManager.GetString("Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        public static string aren {
            get {
                return ResourceManager.GetString("aren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&apos;Sharqiyah Governorate North Police Headquarter.
        /// </summary>
        public static string ASharqiyah {
            get {
                return ResourceManager.GetString("ASharqiyah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&apos;Sharqiyah Governorate South Police Headquarter.
        /// </summary>
        public static string ASharqiyahG {
            get {
                return ResourceManager.GetString("ASharqiyahG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bootstrap.min.css.
        /// </summary>
        public static string bootstrap {
            get {
                return ResourceManager.GetString("bootstrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Civil Defense.
        /// </summary>
        public static string CivilDefense {
            get {
                return ResourceManager.GetString("CivilDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Civil Status.
        /// </summary>
        public static string CivilStatus {
            get {
                return ResourceManager.GetString("CivilStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        public static string clickhere {
            get {
                return ResourceManager.GetString("clickhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Combatting Drugs &amp;Psychotropic Substances.
        /// </summary>
        public static string CombattingDrugs {
            get {
                return ResourceManager.GetString("CombattingDrugs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Services.
        /// </summary>
        public static string common {
            get {
                return ResourceManager.GetString("common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate of Communication.
        /// </summary>
        public static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies services.
        /// </summary>
        public static string companyserv {
            get {
                return ResourceManager.GetString("companyserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactus {
            get {
                return ResourceManager.GetString("contactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string contactuspage {
            get {
                return ResourceManager.GetString("contactuspage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute with Us.
        /// </summary>
        public static string contribute {
            get {
                return ResourceManager.GetString("contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Oman Police - Directorate of Public Relation.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main_styles.css.
        /// </summary>
        public static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customs Service.
        /// </summary>
        public static string custom {
            get {
                return ResourceManager.GetString("custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Customs.
        /// </summary>
        public static string Customs {
            get {
                return ResourceManager.GetString("Customs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Development and Scrutiny.
        /// </summary>
        public static string DevelopmentandScrutiny {
            get {
                return ResourceManager.GetString("DevelopmentandScrutiny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhofar Governorate Police Headquarter.
        /// </summary>
        public static string Dhofar {
            get {
                return ResourceManager.GetString("Dhofar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhofar Governorate Police Headquarter.
        /// </summary>
        public static string DhofarGovernoratePoliceHeadquarter {
            get {
                return ResourceManager.GetString("DhofarGovernoratePoliceHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safty tips.
        /// </summary>
        public static string dlil {
            get {
                return ResourceManager.GetString("dlil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downlaod.
        /// </summary>
        public static string downlaod {
            get {
                return ResourceManager.GetString("downlaod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Directorate of Public Relation.
        /// </summary>
        public static string dpr {
            get {
                return ResourceManager.GetString("dpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Clearance Certificate Validity.
        /// </summary>
        public static string electroniccertificate {
            get {
                return ResourceManager.GetString("electroniccertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact.
        /// </summary>
        public static string emergnc {
            get {
                return ResourceManager.GetString("emergnc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Numbers.
        /// </summary>
        public static string emergncy {
            get {
                return ResourceManager.GetString("emergncy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronic-Visa.
        /// </summary>
        public static string evisa {
            get {
                return ResourceManager.GetString("evisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Financial Affairs.
        /// </summary>
        public static string FinancialAffairs {
            get {
                return ResourceManager.GetString("FinancialAffairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial Inquiries Division.
        /// </summary>
        public static string FinancialInquiries {
            get {
                return ResourceManager.GetString("FinancialInquiries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string fineamount {
            get {
                return ResourceManager.GetString("fineamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string fineclass {
            get {
                return ResourceManager.GetString("fineclass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine Description.
        /// </summary>
        public static string finedesc {
            get {
                return ResourceManager.GetString("finedesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string finepoint {
            get {
                return ResourceManager.GetString("finepoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms&amp;Conditions.
        /// </summary>
        public static string footer1 {
            get {
                return ResourceManager.GetString("footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string footer2 {
            get {
                return ResourceManager.GetString("footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polices.
        /// </summary>
        public static string footer3 {
            get {
                return ResourceManager.GetString("footer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string footer4 {
            get {
                return ResourceManager.GetString("footer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string footer5 {
            get {
                return ResourceManager.GetString("footer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string footer6 {
            get {
                return ResourceManager.GetString("footer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Oman Police.
        /// </summary>
        public static string footertitile {
            get {
                return ResourceManager.GetString("footertitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Directorate.
        /// </summary>
        public static string GeneralDirectorate {
            get {
                return ResourceManager.GetString("GeneralDirectorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Prisons.
        /// </summary>
        public static string GeneralofPrisons {
            get {
                return ResourceManager.GetString("GeneralofPrisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Human Resources.
        /// </summary>
        public static string HumanResources {
            get {
                return ResourceManager.GetString("HumanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Links.
        /// </summary>
        public static string importantlinks {
            get {
                return ResourceManager.GetString("importantlinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Information Technology.
        /// </summary>
        public static string InformationTechnology {
            get {
                return ResourceManager.GetString("InformationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate Genera of Inquiries and Criminal Investigations.
        /// </summary>
        public static string InquiriesandCriminalInvestigations {
            get {
                return ResourceManager.GetString("InquiriesandCriminalInvestigations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juvenile Police Division.
        /// </summary>
        public static string JuvenilePolice {
            get {
                return ResourceManager.GetString("JuvenilePolice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Law Name.
        /// </summary>
        public static string lawname {
            get {
                return ResourceManager.GetString("lawname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the Rules and Laws are in arabic language..
        /// </summary>
        public static string lawnote {
            get {
                return ResourceManager.GetString("lawnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        public static string lawnumber {
            get {
                return ResourceManager.GetString("lawnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules &amp; Law.
        /// </summary>
        public static string laws {
            get {
                return ResourceManager.GetString("laws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can downlaod Related Royal Oman Police Rules and Laws PDFs here..
        /// </summary>
        public static string lawtxt {
            get {
                return ResourceManager.GetString("lawtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate of Legal Affairs.
        /// </summary>
        public static string LegalAffairs {
            get {
                return ResourceManager.GetString("LegalAffairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen.
        /// </summary>
        public static string listen {
            get {
                return ResourceManager.GetString("listen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen this page by ReadSpeaker.
        /// </summary>
        public static string listen2 {
            get {
                return ResourceManager.GetString("listen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_uk.
        /// </summary>
        public static string listen3lang {
            get {
                return ResourceManager.GetString("listen3lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Stations Locations.
        /// </summary>
        public static string locationh {
            get {
                return ResourceManager.GetString("locationh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations Directory.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tt.
        /// </summary>
        public static string logistic {
            get {
                return ResourceManager.GetString("logistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo.png.
        /// </summary>
        public static string logo {
            get {
                return ResourceManager.GetString("logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROP News.
        /// </summary>
        public static string md1 {
            get {
                return ResourceManager.GetString("md1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string md2 {
            get {
                return ResourceManager.GetString("md2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Gallery.
        /// </summary>
        public static string md3 {
            get {
                return ResourceManager.GetString("md3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROP Magazine.
        /// </summary>
        public static string md4 {
            get {
                return ResourceManager.GetString("md4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcment.
        /// </summary>
        public static string md5 {
            get {
                return ResourceManager.GetString("md5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&apos;Shurti Assagheer.
        /// </summary>
        public static string md6 {
            get {
                return ResourceManager.GetString("md6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Episodes.
        /// </summary>
        public static string md7 {
            get {
                return ResourceManager.GetString("md7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string md8event {
            get {
                return ResourceManager.GetString("md8event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employment Announcment.
        /// </summary>
        public static string md9 {
            get {
                return ResourceManager.GetString("md9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Center.
        /// </summary>
        public static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Medical Services.
        /// </summary>
        public static string MedicalServices {
            get {
                return ResourceManager.GetString("MedicalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions of magazine.
        /// </summary>
        public static string mgzntxt {
            get {
                return ResourceManager.GetString("mgzntxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string missiontext {
            get {
                return ResourceManager.GetString("missiontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string missiontext2 {
            get {
                return ResourceManager.GetString("missiontext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Ads.
        /// </summary>
        public static string moreads {
            get {
                return ResourceManager.GetString("moreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More News.
        /// </summary>
        public static string morenews {
            get {
                return ResourceManager.GetString("morenews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted Police Division.
        /// </summary>
        public static string Mounted {
            get {
                return ResourceManager.GetString("Mounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musandam Governorate Police Headquarter.
        /// </summary>
        public static string Musandam {
            get {
                return ResourceManager.GetString("Musandam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musandam Governorate Police Headquarter.
        /// </summary>
        public static string MusandamGovernoratePoliceHeadquarter {
            get {
                return ResourceManager.GetString("MusandamGovernoratePoliceHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscat Governorate Police Headquarter.
        /// </summary>
        public static string Muscat {
            get {
                return ResourceManager.GetString("Muscat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muscat Governorate Police Headquarter.
        /// </summary>
        public static string MuscatGovernoratePoliceHeadquarter {
            get {
                return ResourceManager.GetString("MuscatGovernoratePoliceHeadquarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Executive Office of the National Committee for Civil Defence.
        /// </summary>
        public static string NationalCommittee {
            get {
                return ResourceManager.GetString("NationalCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string newh {
            get {
                return ResourceManager.GetString("newh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Result !!.
        /// </summary>
        public static string noresult {
            get {
                return ResourceManager.GetString("noresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to officerinst.
        /// </summary>
        public static string officerinst {
            get {
                return ResourceManager.GetString("officerinst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Data.
        /// </summary>
        public static string opendata {
            get {
                return ResourceManager.GetString("opendata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Operations.
        /// </summary>
        public static string Operations {
            get {
                return ResourceManager.GetString("Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Contact.
        /// </summary>
        public static string othercon {
            get {
                return ResourceManager.GetString("othercon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Passport and Residences.
        /// </summary>
        public static string PassportandResidences {
            get {
                return ResourceManager.GetString("PassportandResidences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personals Services.
        /// </summary>
        public static string personalserv {
            get {
                return ResourceManager.GetString("personalserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Department.
        /// </summary>
        public static string photoselect {
            get {
                return ResourceManager.GetString("photoselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Police Aviation.
        /// </summary>
        public static string PoliceAviation {
            get {
                return ResourceManager.GetString("PoliceAviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate of Police Clubs.
        /// </summary>
        public static string PoliceClubs {
            get {
                return ResourceManager.GetString("PoliceClubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate of Police Music.
        /// </summary>
        public static string PoliceMusic {
            get {
                return ResourceManager.GetString("PoliceMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Specialized Commands.
        /// </summary>
        public static string PoliceSpecialized {
            get {
                return ResourceManager.GetString("PoliceSpecialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Oman Police Sports Association.
        /// </summary>
        public static string PoliceSportsAssociation {
            get {
                return ResourceManager.GetString("PoliceSportsAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email: info@rop.gov.om.
        /// </summary>
        public static string premail {
            get {
                return ResourceManager.GetString("premail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Issues.
        /// </summary>
        public static string previousissues {
            get {
                return ResourceManager.GetString("previousissues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Projects and Maintenance.
        /// </summary>
        public static string ProjectsandMaintenance {
            get {
                return ResourceManager.GetString("ProjectsandMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate of Public Relation.
        /// </summary>
        public static string PublicRelation {
            get {
                return ResourceManager.GetString("PublicRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puplic sector Services.
        /// </summary>
        public static string puplicserv {
            get {
                return ResourceManager.GetString("puplicserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string qaboossaid {
            get {
                return ResourceManager.GetString("qaboossaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string readmore {
            get {
                return ResourceManager.GetString("readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Police Headquarters.
        /// </summary>
        public static string RegionalPoliceHeadquarters {
            get {
                return ResourceManager.GetString("RegionalPoliceHeadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Blackmailing.
        /// </summary>
        public static string reprtblck {
            get {
                return ResourceManager.GetString("reprtblck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left.
        /// </summary>
        public static string right {
            get {
                return ResourceManager.GetString("right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right.
        /// </summary>
        public static string rightleft {
            get {
                return ResourceManager.GetString("rightleft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Links.
        /// </summary>
        public static string rlinksh {
            get {
                return ResourceManager.GetString("rlinksh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ropmsg {
            get {
                return ResourceManager.GetString("ropmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ropmsg2 {
            get {
                return ResourceManager.GetString("ropmsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROP Phone Directory.
        /// </summary>
        public static string ropphones {
            get {
                return ResourceManager.GetString("ropphones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Oman Police Services.
        /// </summary>
        public static string ropserv {
            get {
                return ResourceManager.GetString("ropserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Safety Competion.
        /// </summary>
        public static string saftyCompt {
            get {
                return ResourceManager.GetString("saftyCompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search In ...
        /// </summary>
        public static string searchin {
            get {
                return ResourceManager.GetString("searchin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Key.
        /// </summary>
        public static string searchkey {
            get {
                return ResourceManager.GetString("searchkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Fees.
        /// </summary>
        public static string servicesfees {
            get {
                return ResourceManager.GetString("servicesfees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string slider1 {
            get {
                return ResourceManager.GetString("slider1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string slider2 {
            get {
                return ResourceManager.GetString("slider2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string slider3 {
            get {
                return ResourceManager.GetString("slider3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string slider4 {
            get {
                return ResourceManager.GetString("slider4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Notification Service.
        /// </summary>
        public static string smsserv {
            get {
                return ResourceManager.GetString("smsserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        public static string socialh {
            get {
                return ResourceManager.GetString("socialh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized Directorates.
        /// </summary>
        public static string SpecializedDirectorates {
            get {
                return ResourceManager.GetString("SpecializedDirectorates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Security Police Division.
        /// </summary>
        public static string SpecialSecurity {
            get {
                return ResourceManager.GetString("SpecialSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic.
        /// </summary>
        public static string stat {
            get {
                return ResourceManager.GetString("stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey.
        /// </summary>
        public static string survey {
            get {
                return ResourceManager.GetString("survey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMMON SERVICES.
        /// </summary>
        public static string tabcom {
            get {
                return ResourceManager.GetString("tabcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcom1 {
            get {
                return ResourceManager.GetString("tabcom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcom2 {
            get {
                return ResourceManager.GetString("tabcom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcom3 {
            get {
                return ResourceManager.GetString("tabcom3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcom4 {
            get {
                return ResourceManager.GetString("tabcom4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcom5 {
            get {
                return ResourceManager.GetString("tabcom5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcomdet1 {
            get {
                return ResourceManager.GetString("tabcomdet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcomdet2 {
            get {
                return ResourceManager.GetString("tabcomdet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcomdet3 {
            get {
                return ResourceManager.GetString("tabcomdet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcomdet4 {
            get {
                return ResourceManager.GetString("tabcomdet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string tabcomdet5 {
            get {
                return ResourceManager.GetString("tabcomdet5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGROY.
        /// </summary>
        public static string tabour {
            get {
                return ResourceManager.GetString("tabour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tt.
        /// </summary>
        public static string telcom {
            get {
                return ResourceManager.GetString("telcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Royal Oman Police - Home.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Traffic.
        /// </summary>
        public static string Traffic {
            get {
                return ResourceManager.GetString("Traffic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Fines Payment.
        /// </summary>
        public static string trafficfines {
            get {
                return ResourceManager.GetString("trafficfines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Fines Point.
        /// </summary>
        public static string trafficfinespoint {
            get {
                return ResourceManager.GetString("trafficfinespoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorate General of Transport.
        /// </summary>
        public static string Transport {
            get {
                return ResourceManager.GetString("Transport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to twitter.
        /// </summary>
        public static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Civil status personal information.
        /// </summary>
        public static string updatecivil {
            get {
                return ResourceManager.GetString("updatecivil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission&amp;Vision.
        /// </summary>
        public static string v_m {
            get {
                return ResourceManager.GetString("v_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Registration Renewal.
        /// </summary>
        public static string vehicleregistration {
            get {
                return ResourceManager.GetString("vehicleregistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Visa Application Service.
        /// </summary>
        public static string visa {
            get {
                return ResourceManager.GetString("visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa Status.
        /// </summary>
        public static string visastatus {
            get {
                return ResourceManager.GetString("visastatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Times.
        /// </summary>
        public static string worktime {
            get {
                return ResourceManager.GetString("worktime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.
        /// </summary>
        public static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
