//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQCategory
    {
        public FAQCategory()
        {
            this.FAQMains = new HashSet<FAQMain>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryE { get; set; }
        public string CategoryA { get; set; }
    
        public virtual ICollection<FAQMain> FAQMains { get; set; }
    }
}
