//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQMain
    {
        public long FAQID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Language { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Answered { get; set; }
        public Nullable<bool> Publish { get; set; }
        public string AddedBy { get; set; }
        public string Email { get; set; }
        public string ContactInfo { get; set; }
        public string ReferenceNo { get; set; }
        public Nullable<bool> MailSent { get; set; }
    
        public virtual FAQCategory FAQCategory { get; set; }
    }
}
