//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsMain
    {
        public NewsMain()
        {
            this.NewsImages = new HashSet<NewsImage>();
        }
    
        public long NewsID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<System.DateTime> NewsDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Title { get; set; }
        public string Synopsis { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<bool> Archive { get; set; }
        public string Language { get; set; }
    
        public virtual NewsCategory NewsCategory { get; set; }
        public virtual ICollection<NewsImage> NewsImages { get; set; }
    }
}
