//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsImage
    {
        public int ID { get; set; }
        public string Filename { get; set; }
        public string ContentType { get; set; }
        public string Image { get; set; }
        public string Imagesize { get; set; }
        public long NewsID { get; set; }
        public bool Active { get; set; }
    
        public virtual NewsMain NewsMain { get; set; }
    }
}
