//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ROP_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public int Service_Id { get; set; }
        public string Service_Name_Ar { get; set; }
        public string Service_Name_En { get; set; }
        public string Service_Desc_Ar { get; set; }
        public string Service_Desc_En { get; set; }
        public string Service_procedure_Ar { get; set; }
        public string Service_procedure_En { get; set; }
        public string Service_Fees_Ar { get; set; }
        public string Service_Fees_En { get; set; }
        public string Service_Channel_Ar { get; set; }
        public string Service_Channel_En { get; set; }
        public string Service_Terms_Ar { get; set; }
        public string Service_Terms_En { get; set; }
        public string Service_Req_Doc_Ar { get; set; }
        public string Service_Req_Doc_En { get; set; }
        public int Service_Cat_Id { get; set; }
        public string Service_Doc { get; set; }
        public int Service_Provider_Id { get; set; }
        public int services_Status_Id { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual SERVICE_CAT SERVICE_CAT { get; set; }
        public virtual SERVICE_STATUS SERVICE_STATUS { get; set; }
        public virtual SERVICE_PROVIDER SERVICE_PROVIDER { get; set; }
    }
}
